name       : re2
version    : 2018.04.01
release    : 6
source     :
    - https://github.com/google/re2/archive/2018-04-01.tar.gz : 2f945446b71336e7f5a2bcace1abcf0b23fbba368266c6a1be33de3de3b3c912
license    : BSD-3-Clause
component  : programming.library
summary    : RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines
description: |
    RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines like those used in PCRE, Perl, and Python. It is a C++ library.
libsplit   : no
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
