name       : re2
version    : 2018.03.01
release    : 5
source     :
    - https://github.com/google/re2/archive/2018-03-01.tar.gz : 51dc7ee9d1a68ee0209672ac4bdff56766c56606dfcdd57aed022015c4784178
license    : BSD-3-Clause
component  : programming.library
summary    : RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines
description: |
    RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines like those used in PCRE, Perl, and Python. It is a C++ library.
libsplit   : no
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
