name       : re2
version    : 2018.12.01
release    : 7
source     :
    - https://github.com/google/re2/archive/2018-12-01.tar.gz : 715e01685719a4ed68a353ae48249612ef4a7464755c3ecccaceae91ebd34868
license    : BSD-3-Clause
component  : programming.library
summary    : RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines
description: |
    RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines like those used in PCRE, Perl, and Python. It is a C++ library.
libsplit   : no
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
