name       : re2
version    : 2017.12.01
release    : 4
source     :
    - https://github.com/google/re2/archive/2017-12-01.tar.gz : 62797e7cd7cc959419710cd25b075b5f5b247da0e8214d47bf5af9b32128fb0d
license    : BSD-3-Clause
component  : programming.library
summary    : RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines
description: |
    RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines like those used in PCRE, Perl, and Python. It is a C++ library.
libsplit   : no
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
