name       : re2
version    : 2021.9.1
release    : 9
source     :
    - https://github.com/google/re2/archive/refs/tags/2021-09-01.tar.gz : 42a2e1d56b5de252f5d418dc1cc0848e9e52ca22b056453988b18c6195ec7f8d
license    : BSD-3-Clause
component  : programming.library
summary    : RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines
description: |
    RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines like those used in PCRE, Perl, and Python. It is a C++ library.
libsplit   : no
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %make common-install DESTDIR=$installdir prefix=/usr
#check      : |
#    %make test
