name       : re2
version    : 2020.01.01
release    : 8
source     :
    - https://github.com/google/re2/archive/2020-01-01.tar.gz : 7509a34636b7dd2966f7a34440cee1153983fd61a4bf8f759a4f7781b9ceebaf
license    : BSD-3-Clause
component  : programming.library
summary    : RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines
description: |
    RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines like those used in PCRE, Perl, and Python. It is a C++ library.
libsplit   : no
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON
build      : |
    %make
install    : |
    %make_install
#check      : |
#    %make test
