name       : re2
version    : 2017.08.01
release    : 2
source     :
    - https://github.com/google/re2/archive/2017-08-01.tar.gz : 938723dc197125392698c5fcf41acb74877866ff140b81fd50b7314bf26f1636
license    : BSD-3-Clause
component  : programming.library
summary    : RE2 is a fast, safe, thread-friendly alternative to backtracking regular
    expression engines
description: |
    RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines like those used in PCRE, Perl, and Python. It is a C++ library.
patterns   :
    - /usr/include/*
    - /usr/lib/libre2.so
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test

